var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/apps_web_a40246b4._.js")
R.c("server/chunks/ssr/apps_web_2bbdbcfe._.js")
R.c("server/chunks/ssr/apps_web_d085cd03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a08af821._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cd7768f5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c7ffc5ee._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7217f8bf._.js")
R.c("server/chunks/ssr/5bcb1_next_dist_client_components_builtin_global-error_a88e7663.js")
R.c("server/chunks/ssr/[root-of-the-server]__c0dc8b35._.js")
R.c("server/chunks/ssr/5bcb1_next_dist_client_components_277499f7._.js")
R.c("server/chunks/ssr/5bcb1_next_dist_client_components_builtin_forbidden_fa7b5765.js")
R.c("server/chunks/ssr/5bcb1_next_dist_client_components_builtin_unauthorized_2cfa72f6.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_page_actions_a0623280.js")
R.m(79449)
module.exports=R.m(79449).exports
